# Generated by Django 5.2.5 on 2025-08-30 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('engine_oil', '엔진오일팀'), ('insurance', '보험영업팀'), ('happycall', '해피콜팀'), ('admin', '관리부서')], max_length=20, unique=True, verbose_name='부서명')),
                ('display_name', models.CharField(max_length=50, verbose_name='표시명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='부서 관리자')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_datetime', models.DateTimeField(verbose_name='시작 일시')),
                ('end_datetime', models.DateTimeField(verbose_name='종료 일시')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('status', models.CharField(choices=[('pending', '대기'), ('confirmed', '확인됨'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급')], default='normal', max_length=10, verbose_name='우선순위')),
                ('is_confirmed_by_assignee', models.BooleanField(default=False, verbose_name='담당자 확인')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확인 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('ical_uid', models.CharField(blank=True, max_length=255, unique=True, verbose_name='iCal UID')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.department', verbose_name='담당 부서')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schedules', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정',
                'ordering': ['start_datetime'],
            },
        ),
    ]
