# Generated by Django 5.2.5 on 2025-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['display_name'], 'verbose_name': '부서', 'verbose_name_plural': '부서'},
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text='부서에 대한 상세 설명', verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='부서 활성화 여부', verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='department',
            name='display_name',
            field=models.CharField(help_text='사용자에게 표시될 부서명 (예: 엔진오일팀, 보험영업팀)', max_length=50, verbose_name='표시명'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='시스템에서 사용하는 부서 코드 (예: engine_oil, insurance)', max_length=50, unique=True, verbose_name='부서 코드'),
        ),
    ]
