# Generated by Django 5.2.5 on 2025-09-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='사번')),
                ('position', models.CharField(choices=[('staff', '직원'), ('manager', '팀장'), ('director', '부장'), ('ceo', '대표')], default='staff', max_length=20, verbose_name='직급')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='입사일')),
                ('status', models.CharField(choices=[('active', '재직'), ('inactive', '휴직'), ('retired', '퇴사')], default='active', max_length=20, verbose_name='재직상태')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.department', verbose_name='부서')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원',
            },
        ),
    ]
