# Generated by Django 5.2.5 on 2025-09-05 00:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0009_alter_servicehistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyCallTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('script_content', models.TextField(verbose_name='스크립트 내용')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '해피콜 템플릿',
                'verbose_name_plural': '해피콜 템플릿들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HappyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_stage', models.CharField(choices=[('1st_pending', '1차콜 대기'), ('1st_in_progress', '1차콜 진행중'), ('1st_completed', '1차콜 완료'), ('1st_failed', '1차콜 실패'), ('2nd_pending', '2차콜 대기'), ('2nd_in_progress', '2차콜 진행중'), ('2nd_completed', '2차콜 완료'), ('2nd_failed', '2차콜 실패'), ('skip', '건너뜀')], default='1st_pending', max_length=20, verbose_name='콜 단계')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('in_progress', '진행중'), ('completed', '완료'), ('failed', '실패'), ('skip', '건너뜀')], default='pending', max_length=20, verbose_name='상태')),
                ('first_call_scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='1차콜 예정일시')),
                ('first_call_date', models.DateTimeField(blank=True, null=True, verbose_name='1차콜 통화일시')),
                ('first_call_notes', models.TextField(blank=True, verbose_name='1차콜 메모')),
                ('first_call_success', models.BooleanField(blank=True, null=True, verbose_name='1차콜 성공')),
                ('second_call_scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='2차콜 예정일시')),
                ('second_call_date', models.DateTimeField(blank=True, null=True, verbose_name='2차콜 통화일시')),
                ('second_call_notes', models.TextField(blank=True, verbose_name='2차콜 메모')),
                ('second_call_success', models.BooleanField(blank=True, null=True, verbose_name='2차콜 성공')),
                ('overall_satisfaction', models.IntegerField(blank=True, choices=[(5, '매우 만족'), (4, '만족'), (3, '보통'), (2, '불만족'), (1, '매우 불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='전체 만족도')),
                ('service_quality', models.IntegerField(blank=True, choices=[(5, '매우 만족'), (4, '만족'), (3, '보통'), (2, '불만족'), (1, '매우 불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='서비스 품질')),
                ('staff_kindness', models.IntegerField(blank=True, choices=[(5, '매우 만족'), (4, '만족'), (3, '보통'), (2, '불만족'), (1, '매우 불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='직원 친절도')),
                ('price_satisfaction', models.IntegerField(blank=True, choices=[(5, '매우 만족'), (4, '만족'), (3, '보통'), (2, '불만족'), (1, '매우 불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='가격 만족도')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='고객 의견')),
                ('improvement_suggestions', models.TextField(blank=True, verbose_name='개선사항')),
                ('additional_needs', models.TextField(blank=True, verbose_name='추가 요구사항')),
                ('will_revisit', models.BooleanField(blank=True, null=True, verbose_name='재방문 의향')),
                ('recommend_to_others', models.BooleanField(blank=True, null=True, verbose_name='타인 추천 의향')),
                ('total_call_attempts', models.IntegerField(default=0, verbose_name='총 통화 시도 횟수')),
                ('next_call_date', models.DateTimeField(blank=True, null=True, verbose_name='다음 통화 예정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('first_call_caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_calls', to=settings.AUTH_USER_MODEL, verbose_name='1차콜 통화자')),
                ('second_call_caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_calls', to=settings.AUTH_USER_MODEL, verbose_name='2차콜 통화자')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.servicerequest', verbose_name='서비스 요청')),
            ],
            options={
                'verbose_name': '해피콜',
                'verbose_name_plural': '해피콜들',
                'ordering': ['-first_call_scheduled_date', '-created_at'],
            },
        ),
    ]
