# Generated by Django 5.2.5 on 2025-09-05 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('happycall', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='happycall',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='관리자 승인일시'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_calls', to=settings.AUTH_USER_MODEL, verbose_name='관리자 승인자'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='car_insurance_interest',
            field=models.CharField(blank=True, choices=[('very_interested', '매우 관심'), ('interested', '관심있음'), ('neutral', '보통'), ('not_interested', '관심없음'), ('refused', '거부')], max_length=20, null=True, verbose_name='자동차보험 관심도'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='current_insurance_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='현재 보험사'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='customer_rejected',
            field=models.BooleanField(default=False, verbose_name='고객 거부'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='driver_insurance_interest',
            field=models.CharField(blank=True, choices=[('very_interested', '매우 관심'), ('interested', '관심있음'), ('neutral', '보통'), ('not_interested', '관심없음'), ('refused', '거부')], max_length=20, null=True, verbose_name='운전자보험 관심도'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='engine_oil_promotion_interest',
            field=models.BooleanField(blank=True, null=True, verbose_name='엔진오일 프로모션 관심도'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='engine_oil_promotion_notes',
            field=models.TextField(blank=True, verbose_name='엔진오일 프로모션 메모'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='fourth_call_caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_calls', to=settings.AUTH_USER_MODEL, verbose_name='4차콜 통화자'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='fourth_call_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='4차콜 통화일시'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='fourth_call_notes',
            field=models.TextField(blank=True, verbose_name='4차콜 메모'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='fourth_call_scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='4차콜 예정일시'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='fourth_call_success',
            field=models.BooleanField(blank=True, null=True, verbose_name='4차콜 성공'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='insurance_consultation_completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='보험 상담 완료'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='insurance_consultation_requested',
            field=models.BooleanField(blank=True, null=True, verbose_name='보험 상담 요청'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='insurance_consultation_result',
            field=models.TextField(blank=True, verbose_name='보험 상담 결과'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='insurance_policy_applied',
            field=models.BooleanField(blank=True, null=True, verbose_name='보험 가입 신청'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='long_term_customer_notes',
            field=models.TextField(blank=True, verbose_name='장기고객 관리 메모'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='팀장 승인일시'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_calls', to=settings.AUTH_USER_MODEL, verbose_name='팀장 승인자'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='다음 검사 예약일'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='next_inspection_scheduled',
            field=models.BooleanField(blank=True, null=True, verbose_name='다음 검사 예약'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='rejection_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='거부 승인일시'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='rejection_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_approved_calls', to=settings.AUTH_USER_MODEL, verbose_name='거부 승인자'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='거부 사유'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='revenue_count',
            field=models.PositiveIntegerField(default=0, verbose_name='매출전표 수'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='third_call_caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_calls', to=settings.AUTH_USER_MODEL, verbose_name='3차콜 통화자'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='third_call_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='3차콜 통화일시'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='third_call_notes',
            field=models.TextField(blank=True, verbose_name='3차콜 메모'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='third_call_scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='3차콜 예정일시'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='third_call_success',
            field=models.BooleanField(blank=True, null=True, verbose_name='3차콜 성공'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='total_revenue_generated',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 발생 매출'),
        ),
        migrations.AlterField(
            model_name='happycall',
            name='call_stage',
            field=models.CharField(choices=[('1st_pending_approval', '1차콜 생성승인대기'), ('1st_pending', '1차콜 대기'), ('1st_in_progress', '1차콜 진행중'), ('1st_completed', '1차콜 완료'), ('1st_failed', '1차콜 실패'), ('2nd_pending_approval', '2차콜 생성승인대기'), ('2nd_pending', '2차콜 대기'), ('2nd_in_progress', '2차콜 진행중'), ('2nd_completed', '2차콜 완료'), ('2nd_failed', '2차콜 실패'), ('3rd_pending_approval', '3차콜 생성승인대기'), ('3rd_pending', '3차콜 대기'), ('3rd_in_progress', '3차콜 진행중'), ('3rd_completed', '3차콜 완료'), ('3rd_failed', '3차콜 실패'), ('4th_pending_approval', '4차콜 생성승인대기'), ('4th_pending', '4차콜 대기'), ('4th_in_progress', '4차콜 진행중'), ('4th_completed', '4차콜 완료'), ('4th_failed', '4차콜 실패'), ('skip', '건너뜀'), ('rejected', '고객거부')], default='1st_pending', max_length=20, verbose_name='콜 단계'),
        ),
        migrations.CreateModel(
            name='CallbackSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_call_stage', models.CharField(max_length=20, verbose_name='원래 콜 단계')),
                ('callback_type', models.CharField(choices=[('customer_request', '고객 요청'), ('failed_call', '콜 실패 후 재시도'), ('specific_time', '특정 시간 재연락')], max_length=20, verbose_name='콜백 유형')),
                ('scheduled_date', models.DateTimeField(verbose_name='예정 일시')),
                ('preferred_time_start', models.TimeField(blank=True, null=True, verbose_name='선호 시작 시간')),
                ('preferred_time_end', models.TimeField(blank=True, null=True, verbose_name='선호 종료 시간')),
                ('status', models.CharField(choices=[('scheduled', '예정됨'), ('completed', '완료됨'), ('failed', '실패'), ('cancelled', '취소됨')], default='scheduled', max_length=20, verbose_name='상태')),
                ('attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='시도 일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('result_notes', models.TextField(blank=True, verbose_name='결과 메모')),
                ('customer_notes', models.TextField(blank=True, verbose_name='고객 요청사항')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='안내 문자 발송')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='문자 발송 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_assignments', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('happy_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happycall.happycall', verbose_name='해피콜')),
            ],
            options={
                'verbose_name': '콜백 스케줄',
                'verbose_name_plural': '콜백 스케줄들',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['happy_call', 'status'], name='happycall_c_happy_c_d8eb8d_idx'), models.Index(fields=['assigned_to', 'scheduled_date'], name='happycall_c_assigne_f84261_idx'), models.Index(fields=['scheduled_date'], name='happycall_c_schedul_001691_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_type', models.CharField(choices=[('all_calls', '모든 콜 거부'), ('specific_stage', '특정 단계 거부'), ('specific_service', '특정 서비스 거부'), ('temporary', '일시적 거부')], max_length=20, verbose_name='거부 유형')),
                ('specific_stages', models.CharField(blank=True, help_text='예: 1st,3rd (쉼표로 구분)', max_length=50, verbose_name='특정 단계')),
                ('specific_services', models.CharField(blank=True, help_text='예: 보험상담,엔진오일 (쉼표로 구분)', max_length=100, verbose_name='특정 서비스')),
                ('customer_reason', models.TextField(verbose_name='고객 거부 사유')),
                ('staff_notes', models.TextField(blank=True, verbose_name='직원 메모')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거부됨')], default='pending', max_length=20, verbose_name='상태')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일시')),
                ('review_notes', models.TextField(blank=True, verbose_name='검토 의견')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='유효 기간')),
                ('happy_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happycall.happycall', verbose_name='해피콜')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_reviews', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
            ],
            options={
                'verbose_name': '콜 거부 요청',
                'verbose_name_plural': '콜 거부 요청들',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['happy_call', 'status'], name='happycall_c_happy_c_705989_idx'), models.Index(fields=['requested_at'], name='happycall_c_request_69265a_idx')],
            },
        ),
        migrations.CreateModel(
            name='HappyCallRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_stage', models.CharField(choices=[('1st', '1차콜'), ('2nd', '2차콜'), ('3rd', '3차콜'), ('4th', '4차콜')], max_length=20, verbose_name='콜 단계')),
                ('revenue_type', models.CharField(choices=[('engine_oil', '엔진오일 프로모션'), ('additional_service', '추가 서비스'), ('insurance_commission', '보험 중개수수료'), ('next_inspection', '다음 검사 예약'), ('other', '기타')], max_length=30, verbose_name='매출 유형')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='상세 설명')),
                ('expected_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='예상 매출액')),
                ('actual_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='실제 매출액')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='수수료율(%)')),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='수수료 금액')),
                ('status', models.CharField(choices=[('proposed', '제안됨'), ('accepted', '수락됨'), ('voucher_created', '전표생성됨'), ('completed', '완료됨'), ('cancelled', '취소됨')], default='proposed', max_length=20, verbose_name='상태')),
                ('proposed_at', models.DateTimeField(auto_now_add=True, verbose_name='제안일시')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='수락일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('happy_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happycall.happycall', verbose_name='해피콜')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='제안자')),
                ('sales_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.salesvoucher', verbose_name='매출전표')),
            ],
            options={
                'verbose_name': '해피콜 매출 기록',
                'verbose_name_plural': '해피콜 매출 기록들',
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['happy_call', 'call_stage'], name='happycall_h_happy_c_9c8e1b_idx'), models.Index(fields=['revenue_type', 'status'], name='happycall_h_revenue_5301ff_idx'), models.Index(fields=['proposed_at'], name='happycall_h_propose_0b0837_idx')],
            },
        ),
    ]
