# Generated by Django 5.2.5 on 2025-09-05 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happycall', '0002_happycall_admin_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFailureRevenueLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_stage', models.CharField(choices=[('1st', '1차콜'), ('2nd', '2차콜'), ('3rd', '3차콜'), ('4th', '4차콜')], max_length=20, verbose_name='실패 단계')),
                ('failure_reason', models.CharField(choices=[('customer_unavailable', '고객 부재'), ('customer_busy', '고객 바쁨'), ('technical_issue', '기술적 문제'), ('customer_refused', '고객 거부'), ('staff_unavailable', '담당자 부재'), ('system_error', '시스템 오류'), ('other', '기타')], max_length=30, verbose_name='실패 사유')),
                ('estimated_revenue_loss', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='예상 매출 손실액')),
                ('sms_notification_sent', models.BooleanField(default=False, verbose_name='안내 문자 발송')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='문자 발송 시간')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 일시')),
                ('callback_scheduled', models.BooleanField(default=False, verbose_name='콜백 예약됨')),
                ('revenue_recovered', models.BooleanField(default=False, verbose_name='매출 회복됨')),
                ('recovered_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='회복된 매출액')),
                ('recovery_date', models.DateTimeField(blank=True, null=True, verbose_name='회복 일자')),
            ],
            options={
                'verbose_name': '콜 실패 매출 손실 기록',
                'verbose_name_plural': '콜 실패 매출 손실 기록들',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueRecoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovered_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='회복된 매출액')),
                ('recovery_source', models.CharField(choices=[('callback_success', '콜백 성공'), ('customer_contact', '고객 직접 연락'), ('next_stage_success', '다음 단계 성공'), ('alternative_channel', '대체 채널'), ('other', '기타')], max_length=30, verbose_name='회복 경로')),
                ('recovery_date', models.DateTimeField(auto_now_add=True, verbose_name='회복 일자')),
                ('recovery_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='원래 손실 대비 회복 비율 (%)', max_digits=5, verbose_name='회복률')),
                ('notes', models.TextField(blank=True, verbose_name='회복 경위')),
            ],
            options={
                'verbose_name': '매출 회복 로그',
                'verbose_name_plural': '매출 회복 로그들',
                'ordering': ['-recovery_date'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('message_content', models.TextField(verbose_name='메시지 내용')),
                ('sms_type', models.CharField(choices=[('call_failure_notification', '콜 실패 안내'), ('callback_reminder', '콜백 리마인더'), ('revenue_proposal', '매출 제안'), ('satisfaction_survey', '만족도 조사'), ('other', '기타')], max_length=30, verbose_name='SMS 유형')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시간')),
                ('success', models.BooleanField(default=False, verbose_name='발송 성공')),
                ('provider_response', models.TextField(blank=True, verbose_name='발송 결과 응답')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='발송 비용')),
                ('delivery_confirmed', models.BooleanField(default=False, verbose_name='전달 확인')),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='전달 확인 시간')),
                ('read_confirmed', models.BooleanField(default=False, verbose_name='읽기 확인')),
                ('read_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='읽기 확인 시간')),
            ],
            options={
                'verbose_name': 'SMS 발송 로그',
                'verbose_name_plural': 'SMS 발송 로그들',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='callrejection',
            options={'ordering': ['-created_at'], 'verbose_name': '고객 거부 요청', 'verbose_name_plural': '고객 거부 요청들'},
        ),
        migrations.RemoveIndex(
            model_name='callrejection',
            name='happycall_c_request_69265a_idx',
        ),
        migrations.RemoveField(
            model_name='callrejection',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='callrejection',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='callrejection',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='callrejection',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='callrejection',
            name='specific_services',
        ),
        migrations.RemoveField(
            model_name='callrejection',
            name='specific_stages',
        ),
        migrations.RemoveField(
            model_name='callrejection',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='callback_count',
            field=models.PositiveIntegerField(default=1, verbose_name='콜백 횟수'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='callback_reason',
            field=models.TextField(blank=True, verbose_name='콜백 사유'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='expected_services',
            field=models.JSONField(blank=True, default=list, help_text='["engine_oil", "insurance", "maintenance"]', verbose_name='예상 서비스 목록'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='max_callback_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='최대 콜백 시도'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='moved_to_next_cycle',
            field=models.BooleanField(default=False, verbose_name='다음 주기로 이동'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='next_cycle_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='다음 주기 예정일'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='original_attempt_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='원래 콜 시도 일시'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='potential_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='예상 매출'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='priority',
            field=models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급')], default='normal', max_length=10, verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='revenue_deferred',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='이월된 매출 기회'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='revenue_opportunity_maintained',
            field=models.BooleanField(default=True, verbose_name='매출 기회 유지'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='sms_delivery_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='SMS 전송 상태'),
        ),
        migrations.AddField(
            model_name='callbackschedule',
            name='sms_template_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='사용된 SMS 템플릿'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='관리자 승인일'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_rejections', to=settings.AUTH_USER_MODEL, verbose_name='관리자 승인자'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='관리자 승인 의견'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='적용일'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callrejection',
            name='current_stage_loss',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='현재 단계 손실'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='customer_attitude',
            field=models.CharField(blank=True, choices=[('polite', '정중함'), ('neutral', '보통'), ('annoyed', '약간 짜증'), ('angry', '화남'), ('very_angry', '매우 화남')], max_length=20, verbose_name='고객 태도'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='customer_reason_details',
            field=models.TextField(blank=True, help_text='기타 선택 시 또는 추가 설명', verbose_name='상세 사유'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='estimated_revenue_loss',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='예상 매출 손실'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='future_contact_ok',
            field=models.CharField(blank=True, choices=[('yes', '필요시 연락 가능'), ('limited', '긴급시에만 연락'), ('no', '일체 연락 거부')], max_length=10, verbose_name='향후 연락 가능성'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='manager_notes',
            field=models.TextField(blank=True, verbose_name='팀장 검토 의견'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='팀장 검토일'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='manager_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviewed_rejections', to=settings.AUTH_USER_MODEL, verbose_name='팀장 검토자'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='rejected_services',
            field=models.JSONField(blank=True, default=list, help_text='["engine_oil", "insurance", "additional_maintenance", "next_inspection"]', verbose_name='거부 서비스 목록'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='rejection_applied',
            field=models.BooleanField(default=False, verbose_name='거부 처리 적용됨'),
        ),
        migrations.AddField(
            model_name='callrejection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='callbackschedule',
            name='callback_type',
            field=models.CharField(choices=[('customer_request', '고객 요청'), ('failed_call', '콜 실패 후 재시도'), ('specific_time', '특정 시간 재연락'), ('technical_issue', '기술적 문제'), ('schedule_conflict', '일정 충돌'), ('follow_up', '후속 연락')], max_length=20, verbose_name='콜백 유형'),
        ),
        migrations.AlterField(
            model_name='callbackschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', '예정됨'), ('in_progress', '진행중'), ('completed', '완료됨'), ('failed', '실패'), ('cancelled', '취소됨')], default='scheduled', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='callrejection',
            name='customer_reason',
            field=models.CharField(choices=[('too_frequent', '전화가 너무 자주 옴'), ('not_interested', '서비스에 관심 없음'), ('financial_burden', '경제적 부담'), ('satisfied_with_current', '현재 서비스에 만족'), ('time_inconvenient', '통화 시간이 불편함'), ('privacy_concerns', '개인정보 우려'), ('bad_experience', '이전 서비스 불만족'), ('competitor_using', '타 업체 이용 중'), ('moving_relocating', '이사/이전 예정'), ('vehicle_sold', '차량 매각'), ('other', '기타')], max_length=30, verbose_name='고객 거부 사유'),
        ),
        migrations.AlterField(
            model_name='callrejection',
            name='rejection_type',
            field=models.CharField(choices=[('all_calls', '모든 해피콜 거부'), ('current_stage', '현재 단계만 거부'), ('remaining_stages', '이후 단계 거부'), ('specific_service', '특정 서비스 거부')], max_length=20, verbose_name='거부 유형'),
        ),
        migrations.AlterField(
            model_name='callrejection',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_rejections', to=settings.AUTH_USER_MODEL, verbose_name='요청자'),
        ),
        migrations.AlterField(
            model_name='callrejection',
            name='staff_notes',
            field=models.TextField(blank=True, verbose_name='담당자 메모'),
        ),
        migrations.AlterField(
            model_name='callrejection',
            name='status',
            field=models.CharField(choices=[('pending_review', '팀장 검토 대기'), ('manager_approved', '팀장 승인 - 관리자 검토 대기'), ('admin_approved', '관리자 최종 승인'), ('rejected', '승인 거부')], default='pending_review', max_length=30, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='happycallrevenue',
            name='status',
            field=models.CharField(choices=[('proposed', '제안됨'), ('accepted', '수락됨'), ('voucher_created', '전표생성됨'), ('completed', '완료됨'), ('cancelled', '취소됨'), ('deferred', '다음 주기 이월')], default='proposed', max_length=20, verbose_name='상태'),
        ),
        migrations.AddIndex(
            model_name='callrejection',
            index=models.Index(fields=['status', 'created_at'], name='happycall_c_status_1c034d_idx'),
        ),
        migrations.AddIndex(
            model_name='callrejection',
            index=models.Index(fields=['rejection_type', 'customer_reason'], name='happycall_c_rejecti_da70de_idx'),
        ),
        migrations.AddField(
            model_name='callfailurerevenueloss',
            name='happy_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happycall.happycall', verbose_name='해피콜'),
        ),
        migrations.AddField(
            model_name='callfailurerevenueloss',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='기록자'),
        ),
        migrations.AddField(
            model_name='revenuerecoverylog',
            name='failure_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_logs', to='happycall.callfailurerevenueloss', verbose_name='실패 기록'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='happy_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happycall.happycall', verbose_name='해피콜'),
        ),
        migrations.AddIndex(
            model_name='callfailurerevenueloss',
            index=models.Index(fields=['happy_call', 'failed_stage'], name='happycall_c_happy_c_81348a_idx'),
        ),
        migrations.AddIndex(
            model_name='callfailurerevenueloss',
            index=models.Index(fields=['failure_reason', 'recorded_at'], name='happycall_c_failure_c4df0a_idx'),
        ),
        migrations.AddIndex(
            model_name='callfailurerevenueloss',
            index=models.Index(fields=['revenue_recovered'], name='happycall_c_revenue_33e6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['happy_call', 'sms_type'], name='happycall_s_happy_c_11bbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['success', 'sent_at'], name='happycall_s_success_de6ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['phone_number'], name='happycall_s_phone_n_b8068a_idx'),
        ),
    ]
