# Generated by Django 5.2.5 on 2025-09-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happycall', '0003_callfailurerevenueloss_revenuerecoverylog_smslog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='happycall',
            name='additional_service_interest',
            field=models.BooleanField(blank=True, null=True, verbose_name='추가 서비스 관심'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='follow_up_needed',
            field=models.BooleanField(blank=True, null=True, verbose_name='후속 조치 필요'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='interested_service_notes',
            field=models.TextField(blank=True, help_text='고객이 관심있어하는 서비스나 후속조치 내용', verbose_name='관심 서비스 메모'),
        ),
        migrations.AddField(
            model_name='happycall',
            name='no_call_request',
            field=models.BooleanField(default=False, help_text='고객이 향후 해피콜을 거부하는 경우', verbose_name='통화 금지 요청'),
        ),
    ]
