# Generated by Django 5.2.5 on 2025-09-08 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happycall', '0004_happycall_additional_service_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happycall',
            name='overall_satisfaction',
            field=models.IntegerField(blank=True, choices=[(3, '만족'), (2, '보통'), (1, '불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='전체 만족도'),
        ),
        migrations.AlterField(
            model_name='happycall',
            name='price_satisfaction',
            field=models.IntegerField(blank=True, choices=[(3, '만족'), (2, '보통'), (1, '불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='가격 만족도'),
        ),
        migrations.AlterField(
            model_name='happycall',
            name='service_quality',
            field=models.IntegerField(blank=True, choices=[(3, '만족'), (2, '보통'), (1, '불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='서비스 품질'),
        ),
        migrations.AlterField(
            model_name='happycall',
            name='staff_kindness',
            field=models.IntegerField(blank=True, choices=[(3, '만족'), (2, '보통'), (1, '불만족')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='직원 친절도'),
        ),
    ]
