# Generated by Django 5.2.5 on 2025-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_detail',
            field=models.TextField(blank=True, help_text='서비스에 대한 세부 설명', verbose_name='세부설명'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle_mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='주행거리(km)'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', '접수대기'), ('scheduled', '일정확정'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='category',
            field=models.CharField(choices=[('engine_oil', '엔진오일교환'), ('maintenance', '정비 점검'), ('insurance', '보험미팅'), ('other', '기타')], max_length=20, verbose_name='카테고리'),
        ),
    ]
