# Generated by Django 5.2.5 on 2025-09-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='예상 서비스 가격 (원)', max_digits=10, null=True, verbose_name='예상 가격'),
        ),
    ]
