# Generated by Django 5.2.5 on 2025-09-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerequest_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='inspection_notes',
            field=models.TextField(blank=True, help_text='검사 관련 특이사항이나 메모', verbose_name='검사 관련 메모'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_inspection_date',
            field=models.DateField(blank=True, help_text='최근 정기검사 또는 종합검사일', null=True, verbose_name='최근 검사일'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='next_inspection_date',
            field=models.DateField(blank=True, help_text='다음 정기검사 또는 종합검사 예정일', null=True, verbose_name='다음 검사일'),
        ),
    ]
