# Generated by Django 5.2.5 on 2025-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_inspection_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_city',
            field=models.CharField(blank=True, help_text='거주 지역 (시/도)', max_length=50, verbose_name='시/도'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_district',
            field=models.CharField(blank=True, help_text='거주 행정동', max_length=100, verbose_name='행정동'),
        ),
    ]
