# Generated by Django 5.2.5 on 2025-09-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicerequest_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer_dong',
            field=models.CharField(blank=True, help_text='거주 행정동 (동/읍/면)', max_length=100, verbose_name='행정동'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='customer_district',
            field=models.CharField(blank=True, help_text='거주 시/군/구', max_length=100, verbose_name='시/군/구'),
        ),
    ]
