# Generated by Django 5.2.5 on 2025-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicerequest_customer_dong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='category',
            field=models.CharField(choices=[('engine_oil', '엔진오일교환'), ('maintenance', '정비 점검'), ('car_inspection', '자동차검사'), ('insurance', '보험미팅'), ('other', '기타')], max_length=20, verbose_name='카테고리'),
        ),
    ]
