# Generated by Django 5.2.5 on 2025-09-02 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0008_alter_servicetype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicehistory',
            options={'ordering': ['-created_at'], 'verbose_name': '서비스 이력', 'verbose_name_plural': '서비스 이력'},
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_city',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_district',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_dong',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='vehicle_mileage',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='vehicle_year',
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='vehicle_condition_notes',
            field=models.TextField(blank=True, verbose_name='차량 상태 메모'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='vehicle_mileage_at_service',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='서비스 시 주행거리'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='고객'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_customer_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='임시 시/도'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_customer_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='임시 시/군/구'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_customer_dong',
            field=models.CharField(blank=True, max_length=100, verbose_name='임시 행정동'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_customer_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='임시 고객명'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='임시 연락처'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_vehicle_mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='임시 주행거리(km)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_vehicle_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='임시 차량모델'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_vehicle_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='임시 차량번호'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='temp_vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='임시 연식'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.vehicle', verbose_name='차량'),
        ),
    ]
