# Generated by Django 5.2.5 on 2025-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='기본 서비스 가격 (원)', max_digits=10, verbose_name='기본 가격'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='category',
            field=models.CharField(help_text='서비스 카테고리 (예: 엔진오일교환, 정비점검, 자동차검사)', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, help_text='서비스에 대한 상세 설명', verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=60, help_text='서비스 수행에 필요한 예상 시간', verbose_name='예상 소요시간(분)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='서비스 유형 활성화 여부', verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(help_text='서비스 이름 (예: 엔진오일 교환, 정기점검)', max_length=100, verbose_name='서비스명'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together={('name', 'category')},
        ),
    ]
