# Generated by Django 5.2.5 on 2025-09-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicetype_updated_at_alter_servicetype_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQuickButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(help_text='버튼에 표시될 텍스트 (예: 5W-30 엔진오일, 부동액 교환)', max_length=100, verbose_name='버튼 텍스트')),
                ('service_content', models.TextField(help_text='버튼 클릭 시 추가될 서비스 내용', verbose_name='서비스 내용')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='버튼 표시 순서 (숫자가 작을수록 먼저 표시)', verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, help_text='버튼 활성화 여부', verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_buttons', to='services.servicetype', verbose_name='서비스 유형')),
            ],
            options={
                'verbose_name': '서비스 빠른 입력 버튼',
                'verbose_name_plural': '서비스 빠른 입력 버튼',
                'ordering': ['service_type', 'display_order', 'button_text'],
                'unique_together': {('service_type', 'button_text')},
            },
        ),
    ]
