# Generated by Django 5.2.5 on 2025-09-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happycall', '0004_happycall_additional_service_interest_and_more'),
        ('services', '0011_servicequickbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='source_happycall',
            field=models.ForeignKey(blank=True, help_text='해피콜에서 추가 서비스 요청으로 생성된 경우', null=True, on_delete=django.db.models.deletion.SET_NULL, to='happycall.happycall', verbose_name='연관 해피콜'),
        ),
    ]
