# Generated by Django 5.2.5 on 2025-09-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicerequest_source_happycall'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_date',
            field=models.DateTimeField(blank=True, help_text='실제 서비스가 수행된 날짜와 시간', null=True, verbose_name='서비스 실행일시'),
        ),
    ]
