# Generated by Django 5.2.5 on 2025-08-29 07:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
                ('color', models.CharField(default='#6B7280', help_text='HEX 색상코드 (예: #3B82F6)', max_length=7, verbose_name='색상')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True, verbose_name='차량번호')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='모델명')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='연식')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '차량',
                'verbose_name_plural': '차량들',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(choices=[('temporary', '임시고객'), ('registered', '정식고객'), ('prospect', '잠재고객'), ('inactive', '비활성')], default='temporary', max_length=20, verbose_name='고객상태')),
                ('customer_type', models.CharField(choices=[('individual', '개인'), ('corporate', '법인')], default='individual', max_length=20, verbose_name='고객구분')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='고객명')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="전화번호는 '010-1234-5678' 형식으로 입력해주세요.", regex='^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$')], verbose_name='휴대폰번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address_main', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('address_detail', models.CharField(blank=True, max_length=200, verbose_name='상세주소')),
                ('business_number', models.CharField(blank=True, max_length=12, verbose_name='사업자번호')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='회사명')),
                ('membership_status', models.CharField(choices=[('none', '비회원'), ('basic', '일반회원'), ('premium', '우수회원'), ('vip', 'VIP회원')], default='none', max_length=20, verbose_name='멤버십')),
                ('membership_join_date', models.DateField(blank=True, null=True, verbose_name='멤버십 가입일')),
                ('membership_expire_date', models.DateField(blank=True, null=True, verbose_name='멤버십 만료일')),
                ('membership_points', models.PositiveIntegerField(default=0, verbose_name='적립포인트')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='마케팅 활용 동의')),
                ('marketing_consent_date', models.DateTimeField(blank=True, null=True, verbose_name='마케팅 동의일')),
                ('preferred_contact_method', models.CharField(choices=[('sms', 'SMS'), ('phone', '전화'), ('email', '이메일')], default='sms', max_length=20, verbose_name='선호 연락방법')),
                ('do_not_contact', models.BooleanField(default=False, verbose_name='연락거부')),
                ('do_not_contact_reason', models.CharField(blank=True, max_length=200, verbose_name='연락거부 사유')),
                ('do_not_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='연락거부 설정일')),
                ('acquisition_source', models.CharField(blank=True, max_length=100, verbose_name='유입경로')),
                ('customer_grade', models.CharField(blank=True, choices=[('A', 'A등급'), ('B', 'B등급'), ('C', 'C등급'), ('D', 'D등급')], max_length=1, verbose_name='고객등급')),
                ('first_service_date', models.DateField(blank=True, null=True, verbose_name='첫 서비스일')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='마지막 서비스일')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='마지막 연락일')),
                ('total_service_count', models.PositiveIntegerField(default=0, verbose_name='총 서비스 횟수')),
                ('total_service_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='총 서비스 금액')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['customer_status'], name='customers_c_custome_58dde4_idx'), models.Index(fields=['membership_status'], name='customers_c_members_044d4c_idx'), models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='거래일시')),
                ('point_type', models.CharField(choices=[('earned', '적립'), ('used', '사용'), ('expired', '만료'), ('adjusted', '조정')], max_length=20, verbose_name='포인트 구분')),
                ('points', models.IntegerField(verbose_name='포인트')),
                ('reason', models.CharField(max_length=200, verbose_name='사유')),
                ('related_service_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='연관 서비스 ID')),
                ('balance_after', models.PositiveIntegerField(verbose_name='거래 후 잔액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='처리일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='customers.customer', verbose_name='고객')),
            ],
            options={
                'verbose_name': '포인트 이력',
                'verbose_name_plural': '포인트 이력들',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='캠페인명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('campaign_type', models.CharField(choices=[('sms', 'SMS'), ('email', '이메일'), ('dm', 'DM우편'), ('phone', '전화마케팅')], max_length=20, verbose_name='캠페인 유형')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('target_criteria', models.TextField(blank=True, verbose_name='타겟 조건')),
                ('status', models.CharField(choices=[('draft', '준비중'), ('active', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='draft', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '마케팅 캠페인',
                'verbose_name_plural': '마케팅 캠페인들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='소유 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='소유 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_ownerships', to='customers.customer', verbose_name='고객')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='customers.vehicle', verbose_name='차량')),
            ],
            options={
                'verbose_name': '고객 차량 소유관계',
                'verbose_name_plural': '고객 차량 소유관계들',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_date', models.DateTimeField(verbose_name='소통일시')),
                ('communication_type', models.CharField(choices=[('consultation', '상담'), ('marketing', '마케팅'), ('complaint', '불만'), ('inquiry', '문의'), ('follow_up', '후속연락')], max_length=20, verbose_name='소통구분')),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('phone', '전화'), ('email', '이메일'), ('visit', '방문')], max_length=20, verbose_name='소통방법')),
                ('direction', models.CharField(choices=[('inbound', '고객→업체'), ('outbound', '업체→고객')], max_length=20, verbose_name='방향')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('result', models.CharField(choices=[('success', '성공'), ('no_answer', '연락안됨'), ('refused', '거부'), ('failed', '실패')], max_length=20, verbose_name='결과')),
                ('follow_up_needed', models.BooleanField(default=False, verbose_name='후속조치 필요')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='후속조치 예정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='customers.customer', verbose_name='고객')),
            ],
            options={
                'verbose_name': '고객 소통이력',
                'verbose_name_plural': '고객 소통이력들',
                'ordering': ['-communication_date'],
                'indexes': [models.Index(fields=['customer', '-communication_date'], name='customers_c_custome_38bc4b_idx'), models.Index(fields=['communication_type', '-communication_date'], name='customers_c_communi_d6e967_idx')],
            },
        ),
        migrations.CreateModel(
            name='HappyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_record_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='연관 서비스 ID')),
                ('call_sequence', models.PositiveIntegerField(choices=[(1, '1차콜'), (2, '2차콜'), (3, '3차콜')], verbose_name='콜 차수')),
                ('scheduled_date', models.DateTimeField(verbose_name='예정일시')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('contact_result', models.CharField(blank=True, choices=[('completed', '연락완료'), ('no_answer', '연락안됨'), ('refused', '거부'), ('wrong_number', '잘못된번호')], max_length=20, verbose_name='연락결과')),
                ('satisfaction_score', models.PositiveIntegerField(blank=True, choices=[(1, '매우불만'), (2, '불만'), (3, '보통'), (4, '만족'), (5, '매우만족')], null=True, verbose_name='만족도')),
                ('complaint_exists', models.BooleanField(default=False, verbose_name='불만사항 있음')),
                ('complaint_details', models.TextField(blank=True, verbose_name='불만내용')),
                ('follow_up_service_needed', models.BooleanField(default=False, verbose_name='추가 서비스 필요')),
                ('next_call_scheduled', models.BooleanField(default=False, verbose_name='다음 콜 예정')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_calls', to='customers.customer', verbose_name='고객')),
            ],
            options={
                'verbose_name': '해피콜',
                'verbose_name_plural': '해피콜들',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['customer', '-scheduled_date'], name='customers_h_custome_9a3d34_idx'), models.Index(fields=['call_sequence', '-scheduled_date'], name='customers_h_call_se_af51b3_idx'), models.Index(fields=['scheduled_date'], name='customers_h_schedul_0ab600_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerCampaignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(verbose_name='발송일시')),
                ('delivery_status', models.CharField(choices=[('sent', '발송완료'), ('failed', '발송실패'), ('refused', '수신거부')], max_length=20, verbose_name='발송상태')),
                ('opened_date', models.DateTimeField(blank=True, null=True, verbose_name='오픈일시')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='반응일시')),
                ('response_type', models.CharField(blank=True, choices=[('interested', '관심표시'), ('purchased', '구매'), ('refused', '거부'), ('no_response', '무반응')], max_length=20, verbose_name='반응유형')),
                ('roi_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='매출발생액')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_history', to='customers.customer', verbose_name='고객')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history', to='customers.marketingcampaign', verbose_name='캠페인')),
            ],
            options={
                'verbose_name': '캠페인 이력',
                'verbose_name_plural': '캠페인 이력들',
                'ordering': ['-sent_date'],
                'unique_together': {('customer', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='태그 부여일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='태그 부여자')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='customers.customer', verbose_name='고객')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='customers.tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '고객 태그',
                'verbose_name_plural': '고객 태그들',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'tag')},
            },
        ),
    ]
