# Generated by Django 5.2.5 on 2025-09-05 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_customers', to=settings.AUTH_USER_MODEL, verbose_name='금지 설정자'),
        ),
        migrations.AddField(
            model_name='customer',
            name='banned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='금지 설정일'),
        ),
        migrations.AddField(
            model_name='customer',
            name='banned_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='금지 사유'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='악성 고객, 서비스 거부 등 금지고객 지정', verbose_name='금지고객'),
        ),
        migrations.AddField(
            model_name='customer',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='필수: 개인정보 수집/이용 동의', verbose_name='개인정보 처리 동의'),
        ),
        migrations.AddField(
            model_name='customer',
            name='privacy_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='개인정보 동의일'),
        ),
    ]
