# Generated by Django 5.2.5 on 2025-09-03 01:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0009_alter_servicehistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('business_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='사업자번호')),
                ('representative', models.CharField(blank=True, max_length=50, verbose_name='대표자명')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='계좌번호')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='은행명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성상태')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '공급업체',
                'verbose_name_plural': '공급업체들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='계정코드')),
                ('name', models.CharField(max_length=100, verbose_name='계정명')),
                ('category_type', models.CharField(choices=[('asset', '자산'), ('liability', '부채'), ('equity', '자본'), ('revenue', '수익'), ('expense', '비용')], max_length=10, verbose_name='계정구분')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingcategory', verbose_name='상위계정')),
            ],
            options={
                'verbose_name': '계정과목',
                'verbose_name_plural': '계정과목들',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=20, unique=True, verbose_name='분개번호')),
                ('entry_date', models.DateField(verbose_name='분개일자')),
                ('description', models.CharField(max_length=200, verbose_name='적요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '분개장',
                'verbose_name_plural': '분개장들',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='차변금액')),
                ('credit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='대변금액')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='적요')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingcategory', verbose_name='계정과목')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': '분개 세부항목',
                'verbose_name_plural': '분개 세부항목들',
            },
        ),
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=20, unique=True, verbose_name='전표번호')),
                ('purchase_date', models.DateField(verbose_name='매입일자')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총금액')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='부가세')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('card', '카드'), ('transfer', '계좌이체'), ('check', '수표'), ('credit', '외상')], default='transfer', max_length=20, verbose_name='결제방법')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='결제일자')),
                ('is_paid', models.BooleanField(default=False, verbose_name='결제완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.supplier', verbose_name='공급업체')),
            ],
            options={
                'verbose_name': '매입전표',
                'verbose_name_plural': '매입전표들',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='purchase_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.purchasevoucher', verbose_name='매입전표'),
        ),
        migrations.CreateModel(
            name='PurchaseVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='품목명')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='규격')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('unit', models.CharField(default='개', max_length=10, verbose_name='단위')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingcategory', verbose_name='계정과목')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.purchasevoucher')),
            ],
            options={
                'verbose_name': '매입전표 항목',
                'verbose_name_plural': '매입전표 항목들',
            },
        ),
        migrations.CreateModel(
            name='SalesVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=20, unique=True, verbose_name='전표번호')),
                ('sales_date', models.DateField(verbose_name='매출일자')),
                ('customer_name', models.CharField(max_length=100, verbose_name='고객명')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='총금액')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='부가세')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='적요')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('card', '카드'), ('transfer', '계좌이체'), ('check', '수표'), ('credit', '외상')], default='card', max_length=20, verbose_name='결제방법')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='입금일자')),
                ('is_received', models.BooleanField(default=False, verbose_name='입금완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicerequest', verbose_name='서비스 요청')),
            ],
            options={
                'verbose_name': '매출전표',
                'verbose_name_plural': '매출전표들',
                'ordering': ['-sales_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sales_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.salesvoucher', verbose_name='매출전표'),
        ),
        migrations.CreateModel(
            name='SalesVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='품목명')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='규격')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('unit', models.CharField(default='건', max_length=10, verbose_name='단위')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingcategory', verbose_name='계정과목')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.salesvoucher')),
            ],
            options={
                'verbose_name': '매출전표 항목',
                'verbose_name_plural': '매출전표 항목들',
            },
        ),
    ]
