# Generated by Django 5.2.5 on 2025-09-05 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('happycall', '0002_happycall_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='happy_call_revenue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='happycall.happycallrevenue', verbose_name='해피콜 매출 기록'),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='revenue_source',
            field=models.CharField(choices=[('direct', '직접 서비스'), ('happy_call_1st', '1차 해피콜'), ('happy_call_2nd', '2차 해피콜'), ('happy_call_3rd', '3차 해피콜'), ('happy_call_4th', '4차 해피콜'), ('other', '기타')], default='direct', max_length=30, verbose_name='매출 출처'),
        ),
    ]
